# Generated by Django 5.0.6 on 2026-03-08 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'மாவட்டம்',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Jathagam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ஜாதகம்',
            },
        ),
        migrations.CreateModel(
            name='Nachathiram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'நட்சத்திரம்',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'தொழில்',
            },
        ),
        migrations.CreateModel(
            name='Rasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ராசி',
            },
        ),
        migrations.CreateModel(
            name='ShadowCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'நிலுவை விண்ணப்பம்',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'மாநிலம்',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='இருப்பிடம்')),
                ('address', models.TextField(verbose_name='முகவரி')),
                ('phone', models.CharField(max_length=15, verbose_name='தொலைபேசி')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'ஆண்'), ('F', 'பெண்')], max_length=1, verbose_name='பாலினம்')),
                ('name', models.CharField(max_length=200, verbose_name='பெயர்')),
                ('date_of_birth', models.DateField(verbose_name='பிறந்த தேதி')),
                ('profession_comments', models.TextField(blank=True, verbose_name='தொழில் விவரம்')),
                ('educational_qualification', models.CharField(max_length=200, verbose_name='கல்வித் தகுதி')),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='வருடாந்திர வருமானம்')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='மாத சம்பளம்')),
                ('height', models.CharField(max_length=20, verbose_name='உயரம்')),
                ('caste', models.CharField(max_length=100, verbose_name='சாதி')),
                ('sub_caste', models.CharField(blank=True, max_length=100, verbose_name='உட்சாதி')),
                ('sevadosham', models.CharField(choices=[('yes', 'உண்டு'), ('no', 'இல்லை'), ('partial', 'பாதி')], max_length=10, verbose_name='செவ்வாய் தோஷம்')),
                ('ragu_kethu', models.CharField(blank=True, max_length=50, verbose_name='ராகு/கேது')),
                ('property_value', models.CharField(blank=True, max_length=200, verbose_name='சொத்து மதிப்பு')),
                ('status', models.CharField(choices=[('active', 'செயலில்'), ('inactive', 'செயலற்று')], default='active', max_length=10, verbose_name='நிலை')),
                ('premium_start_date', models.DateField(blank=True, null=True, verbose_name='பிரீமியம் தொடக்க தேதி')),
                ('premium_end_date', models.DateField(blank=True, null=True, verbose_name='பிரீமியம் முடிவு தேதி')),
                ('is_paid', models.BooleanField(default=True, verbose_name='கட்டணம் செலுத்தியது')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=True)),
                ('jathagam_h1', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 1 (லக்னம்)')),
                ('jathagam_h2', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 2')),
                ('jathagam_h3', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 3')),
                ('jathagam_h4', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 4')),
                ('jathagam_h5', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 5')),
                ('jathagam_h6', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 6')),
                ('jathagam_h7', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 7')),
                ('jathagam_h8', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 8')),
                ('jathagam_h9', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 9')),
                ('jathagam_h10', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 10')),
                ('jathagam_h11', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 11')),
                ('jathagam_h12', models.CharField(blank=True, choices=[('', '-'), ('லக்னம்', 'லக்னம்'), ('சூ', 'சூரியன் (சூ)'), ('ச', 'சந்திரன் (ச)'), ('செ', 'செவ்வாய் (செ)'), ('பு', 'புதன் (பு)'), ('கு', 'குரு (கு)'), ('சுக்', 'சுக்கிரன் (சுக்)'), ('சனி', 'சனி'), ('ரா', 'ராகு (ரா)'), ('கே', 'கேது (கே)'), ('லக்,சூ', 'லக்னம் + சூரியன்'), ('லக்,ச', 'லக்னம் + சந்திரன்'), ('லக்,செ', 'லக்னம் + செவ்வாய்'), ('லக்,பு', 'லக்னம் + புதன்'), ('லக்,கு', 'லக்னம் + குரு'), ('லக்,சுக்', 'லக்னம் + சுக்கிரன்'), ('லக்,சனி', 'லக்னம் + சனி'), ('சூ,ச', 'சூரியன் + சந்திரன்'), ('சூ,செ', 'சூரியன் + செவ்வாய்'), ('சூ,பு', 'சூரியன் + புதன்'), ('சூ,கு', 'சூரியன் + குரு'), ('சூ,சனி', 'சூரியன் + சனி'), ('ச,செ', 'சந்திரன் + செவ்வாய்'), ('ச,கு', 'சந்திரன் + குரு'), ('ச,சனி', 'சந்திரன் + சனி'), ('செ,கு', 'செவ்வாய் + குரு'), ('செ,சனி', 'செவ்வாய் + சனி'), ('பு,சுக்', 'புதன் + சுக்கிரன்'), ('கு,சனி', 'குரு + சனி'), ('ரா,கே', 'ராகு + கேது')], max_length=50, verbose_name='வீடு 12')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name='தந்தை பெயர்')),
                ('mother_name', models.CharField(blank=True, max_length=200, verbose_name='தாய் பெயர்')),
                ('siblings_info', models.TextField(blank=True, verbose_name='உடன்பிறந்தோர் விவரம்')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.district', verbose_name='மாவட்டம்')),
                ('jathagam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.jathagam', verbose_name='ஜாதகம்')),
                ('nachathiram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.nachathiram', verbose_name='நட்சத்திரம்')),
                ('father_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathers', to='matrimony.profession', verbose_name='தந்தை தொழில்')),
                ('mother_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers', to='matrimony.profession', verbose_name='தாய் தொழில்')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.profession', verbose_name='தொழில்')),
                ('rasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.rasi', verbose_name='ராசி')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.state', verbose_name='மாநிலம்')),
            ],
            options={
                'verbose_name': 'விண்ணப்பதாரர்',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='matrimony.candidate')),
            ],
            options={
                'verbose_name': 'புகைப்படம்',
            },
        ),
        migrations.AddField(
            model_name='nachathiram',
            name='rasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.rasi'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.state'),
        ),
    ]
