# Generated by Django 5.0.6 on 2026-03-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='குறியீடு')),
                ('name', models.CharField(max_length=50, verbose_name='பெயர்')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'சொந்த வீடு',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TamilDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='தமிழ் தேதி')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'தமிழ் தேதி',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TamilMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='தமிழ் மாதம்')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'தமிழ் மாதம்',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TamilYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='தமிழ் வருடம்')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'தமிழ் வருடம்',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='caste',
            field=models.CharField(blank=True, max_length=100, verbose_name='சாதி'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.district', verbose_name='மாவட்டம்'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='கல்வித் தகுதி'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='height',
            field=models.CharField(blank=True, max_length=20, verbose_name='உயரம்'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='nachathiram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.nachathiram', verbose_name='நட்சத்திரம்'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.profession', verbose_name='தொழில்'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='rasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.rasi', verbose_name='ராசி'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.state', verbose_name='மாநிலம்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='caste',
            field=models.CharField(blank=True, max_length=100, verbose_name='சாதி'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.district', verbose_name='மாவட்டம்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='கல்வித் தகுதி'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='height',
            field=models.CharField(blank=True, max_length=20, verbose_name='உயரம்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='nachathiram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.nachathiram', verbose_name='நட்சத்திரம்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.profession', verbose_name='தொழில்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='rasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.rasi', verbose_name='ராசி'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.state', verbose_name='மாநிலம்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='own_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.ownhouse', verbose_name='சொந்த வீடு'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='own_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.ownhouse', verbose_name='சொந்த வீடு'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='tamil_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilday', verbose_name='தமிழ் தேதி'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='tamil_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilday', verbose_name='தமிழ் தேதி'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='tamil_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilmonth', verbose_name='தமிழ் மாதம்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='tamil_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilmonth', verbose_name='தமிழ் மாதம்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='tamil_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilyear', verbose_name='தமிழ் வருடம்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='tamil_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilyear', verbose_name='தமிழ் வருடம்'),
        ),
    ]
