# Generated by Django 5.0.6 on 2026-03-08 17:13

import matrimony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatephoto',
            name='photo',
            field=models.ImageField(upload_to=matrimony.models.candidate_photo_path),
        ),
    ]
