# Generated by Django 5.0.6 on 2026-03-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_ownhouse_tamilday_tamilmonth_tamilyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamilday',
            name='name',
            field=models.CharField(max_length=50, verbose_name='தமிழ் தேதி'),
        ),
    ]
