# Generated by Django 5.0.6 on 2026-03-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_alter_tamilday_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='பிறப்பு வரிசை')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'பிறப்பு வரிசை',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='பிறந்த ஊர்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='native_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='பூர்வீகம்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='thisai_iruppu',
            field=models.CharField(blank=True, max_length=100, verbose_name='திசை இருப்பு'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='பிறந்த ஊர்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='native_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='பூர்வீகம்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='thisai_iruppu',
            field=models.CharField(blank=True, max_length=100, verbose_name='திசை இருப்பு'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='birth_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.birthorder', verbose_name='பிறப்பு வரிசை'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='birth_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.birthorder', verbose_name='பிறப்பு வரிசை'),
        ),
    ]
