# Generated by Django 5.0.6 on 2026-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_birthorder_femalecandidate_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalecandidate',
            name='birth_time',
            field=models.TimeField(blank=True, null=True, verbose_name='பிறந்த நேரம்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='birth_time',
            field=models.TimeField(blank=True, null=True, verbose_name='பிறந்த நேரம்'),
        ),
    ]
