# Generated by Django 5.0.6 on 2026-03-09 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_femalecandidate_birth_time_malecandidate_birth_time'),
    ]

    operations = [
           migrations.RunSQL(
        "ALTER TABLE matrimony_malecandidate ALTER COLUMN caste DROP NOT NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "ALTER TABLE matrimony_malecandidate ALTER COLUMN height DROP NOT NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "ALTER TABLE matrimony_malecandidate ALTER COLUMN sub_caste DROP NOT NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "ALTER TABLE matrimony_femalecandidate ALTER COLUMN caste DROP NOT NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "ALTER TABLE matrimony_femalecandidate ALTER COLUMN height DROP NOT NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "ALTER TABLE matrimony_femalecandidate ALTER COLUMN sub_caste DROP NOT NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "UPDATE matrimony_malecandidate SET caste=NULL, sub_caste=NULL, height=NULL",
        migrations.RunSQL.noop
    ),
    migrations.RunSQL(
        "UPDATE matrimony_femalecandidate SET caste=NULL, sub_caste=NULL, height=NULL",
        migrations.RunSQL.noop
    ),
         
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='சாதி')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'சாதி',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Complexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='நிறம்')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'நிறம்',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='உயரம்')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'உயரம்',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.caste', verbose_name='சாதி'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.caste', verbose_name='சாதி'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='complexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.complexion', verbose_name='நிறம்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='complexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.complexion', verbose_name='நிறம்'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.height', verbose_name='உயரம்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.height', verbose_name='உயரம்'),
        ),
        migrations.CreateModel(
            name='SubCaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='உட்சாதி')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_castes', to='matrimony.caste', verbose_name='சாதி')),
            ],
            options={
                'verbose_name': 'உட்சாதி',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='sub_caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.subcaste', verbose_name='உட்சாதி'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='sub_caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.subcaste', verbose_name='உட்சாதி'),
        ),
    ]
