# Generated by Django 5.0.6 on 2026-03-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0006_caste_complexion_height_alter_femalecandidate_caste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='திருமண நிலை')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'திருமண நிலை',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='உறவு')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'உறவு',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_gender', models.CharField(choices=[('M', 'ஆண்'), ('F', 'பெண்')], max_length=1)),
                ('candidate_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200, verbose_name='பெயர்')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='படிப்பு')),
                ('job_info', models.CharField(blank=True, max_length=200, verbose_name='பணி விவரம்')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.maritalstatus', verbose_name='திருமணம்')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.relation', verbose_name='உறவு')),
            ],
            options={
                'verbose_name': 'குடும்பத்தினர்',
                'ordering': ['order', 'id'],
            },
        ),
    ]
