# Generated by Django 5.0.6 on 2026-03-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0007_maritalstatus_relation_familymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalecandidate',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='father_profession',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='mother_profession',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='siblings_info',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='father_profession',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='mother_profession',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='siblings_info',
        ),
    ]
