# Generated by Django 5.0.6 on 2026-03-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0008_remove_femalecandidate_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalecandidate',
            name='ragu_kethu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matrimony.ownhouse', verbose_name='ராகு/கேது'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='ragu_kethu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matrimony.ownhouse', verbose_name='ராகு/கேது'),
        ),
    ]
