# Generated by Django 5.0.6 on 2026-03-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0009_alter_femalecandidate_ragu_kethu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalecandidate',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='முகவரி வரி 1'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='முகவரி வரி 2'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='address_line3',
            field=models.CharField(blank=True, max_length=200, verbose_name='முகவரி வரி 3'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='address_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='பெயர்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='கைபேசி எண்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, verbose_name='பின்கோட்'),
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='வாட்ஸ்அப் எண்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='முகவரி வரி 1'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='முகவரி வரி 2'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='address_line3',
            field=models.CharField(blank=True, max_length=200, verbose_name='முகவரி வரி 3'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='address_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='பெயர்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='கைபேசி எண்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, verbose_name='பின்கோட்'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='வாட்ஸ்அப் எண்'),
        ),
    ]
