# Generated by Django 5.0.6 on 2026-03-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0010_femalecandidate_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcaste',
            options={'ordering': ['order', 'name'], 'verbose_name': 'உட்பிரிவு'},
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='sub_caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.subcaste', verbose_name='உட்பிரிவு'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='sub_caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.subcaste', verbose_name='உட்பிரிவு'),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='name',
            field=models.CharField(max_length=100, verbose_name='உட்பிரிவு'),
        ),
    ]
