# Generated by Django 5.0.6 on 2026-03-13 05:14

import django.db.models.deletion
import matrimony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0013_remove_jathagam_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['order', 'name'], 'verbose_name': 'மாவட்டம்'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['order', 'name'], 'verbose_name': 'மாநிலம்'},
        ),
        migrations.AddField(
            model_name='femalecandidate',
            name='jathagam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.jathagamtype', verbose_name='ஜாதகம் வகை'),
        ),
        migrations.AddField(
            model_name='malecandidate',
            name='jathagam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.jathagamtype', verbose_name='ஜாதகம் வகை'),
        ),
        migrations.AlterField(
            model_name='candidatephoto',
            name='photo',
            field=models.ImageField(upload_to=matrimony.models.candidate_photo_upload),
        ),
    ]
