# Generated by Django 5.0.6 on 2026-03-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0017_adminprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='jathagam_type',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='jathagam_type',
        ),
    ]
