# Generated by Django 5.0.6 on 2026-03-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0020_add_lagnam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalecandidate',
            name='tamil_kizhamai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilkizhamai', verbose_name='தமிழ் கிழமை'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='tamil_kizhamai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.tamilkizhamai', verbose_name='தமிழ் கிழமை'),
        ),
        migrations.AlterField(
            model_name='tamildate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tamilkizhamai',
            name='name',
            field=models.CharField(max_length=50, verbose_name='தமிழ் கிழமை'),
        ),
    ]
