# Generated by Django 5.0.6 on 2026-03-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0021_alter_femalecandidate_tamil_kizhamai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h1',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h10',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h11',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h12',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h2',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h3',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h4',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h5',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h6',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h7',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h8',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='navamsam_h9',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h1',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h10',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h11',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h12',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h2',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h3',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h4',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h5',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h6',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h7',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h8',
        ),
        migrations.RemoveField(
            model_name='femalecandidate',
            name='rasi_h9',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h1',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h10',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h11',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h12',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h2',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h3',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h4',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h5',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h6',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h7',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h8',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='navamsam_h9',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h1',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h10',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h11',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h12',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h2',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h3',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h4',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h5',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h6',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h7',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h8',
        ),
        migrations.RemoveField(
            model_name='malecandidate',
            name='rasi_h9',
        ),
        migrations.CreateModel(
            name='JathagamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_gender', models.CharField(choices=[('M', 'ஆண்'), ('F', 'பெண்')], max_length=1, verbose_name='பாலினம்')),
                ('candidate_id', models.PositiveIntegerField(verbose_name='விண்ணப்பதாரர் ID')),
                ('chart_type', models.CharField(choices=[('R', 'ராசி'), ('N', 'நவாம்சம்')], max_length=1, verbose_name='சார்ட் வகை')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='வீடு எண்')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='வரிசை')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony.planet', verbose_name='கோள்')),
            ],
            options={
                'verbose_name': 'ஜாதகம் பதிவு',
                'ordering': ['chart_type', 'house_number', 'order'],
                'indexes': [models.Index(fields=['candidate_gender', 'candidate_id'], name='jathagam_candidate_idx'), models.Index(fields=['candidate_gender', 'candidate_id', 'chart_type'], name='jathagam_candidate_chart_idx')],
            },
        ),
    ]
