# Generated by Django 5.0.6 on 2026-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0027_expectations_biotoken_biosendlog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidateexpectation',
            name='unique_candidate_expectation',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_is_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_paid_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_uid_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_old_reg_no_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_rasi_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_nachathiram_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_dob_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_salary_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_premium_end_idx',
        ),
        migrations.RemoveIndex(
            model_name='femalecandidate',
            name='female_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_is_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_paid_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_uid_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_old_reg_no_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_rasi_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_nachathiram_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_dob_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_salary_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_premium_end_idx',
        ),
        migrations.RemoveIndex(
            model_name='malecandidate',
            name='male_created_at_idx',
        ),
        migrations.AlterField(
            model_name='biosendlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='biotoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidateexpectation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expectationcomplexion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expectationdistrict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expectationnachathiram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expectationprofession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expectationsubcaste',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='femalecandidate',
            name='old_reg_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='ப.பதிவு எண்'),
        ),
        migrations.AlterField(
            model_name='malecandidate',
            name='old_reg_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='ப.பதிவு எண்'),
        ),
        migrations.AlterField(
            model_name='premiumtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ragukethu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateexpectation',
            unique_together={('candidate_gender', 'candidate_id')},
        ),
    ]
